services:
  dev:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/home
  postgres:
    image: postgres:15.2
    environment:
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:7.0
  mongo:
    image: 'mongo:6.0'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
